covid_stats/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('world_population/', views.world_population, name='world_population'),
    path('covid_total_cases/', views.covid_total_cases, name='covid_total_cases'),
    path('today_cases/', views.today_cases, name='today_cases'),
    path('total_deaths/', views.total_deaths, name='total_deaths'),
    path('cases_per_one_million/', views.cases_per_one_million, name='cases_per_one_million'),
]

covid_visualization/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('covid_stats.urls', 'covid_stats'), namespace='covid_stats')),
]

covid_stats/models.py
from django.db import models

# Create your models here.

covid_stats/views.py
from django.shortcuts import render
import requests
import pygal
from pygal.style import LightColorizedStyle as LCS, RotateStyle as RS, LightenStyle as LS 

def index(request):
    return render(request, 'covid_stats/index.html')

def world_population(request):
    url = 'https://disease.sh/v3/covid-19/countries'
    api_request = requests.get(url)

    if api_request.status_code != 200:
        print("failed to fetch the API...")
        quit()

    response = api_request.json()
    world_population = {}
    for country in response:
        if country["countryInfo"]["iso2"] == None:
            continue 

        world_population[country["countryInfo"]["iso2"].lower()] = country["population"]


    world_map = pygal.maps.world.World()
    world_map.style = RS('#FFF033', base_style=LCS)
    world_map.add('world population', world_population)
    world_map.render_to_file('covid_stats/static/covid_stats/images/world_population.svg')

    return render(request, 'covid_stats/world_population.html')

def covid_total_cases(request):
    url = 'https://disease.sh/v3/covid-19/countries'
    api_request = requests.get(url)

    if api_request.status_code != 200:
        print("failed to fetch the API...")
        quit()

    response = api_request.json()
    covid_total_cases = {}
    for country in response:
        if country["countryInfo"]["iso2"] == None:
            continue 

        covid_total_cases[country["countryInfo"]["iso2"].lower()] = country["cases"]


    world_map = pygal.maps.world.World()
    world_map.style = RS('#FF6E33', base_style=LCS)
    world_map.add('covid total cases', covid_total_cases)
    world_map.render_to_file('covid_stats/static/covid_stats/images/covid_total_cases.svg')

    return render(request, 'covid_stats/covid_total_cases.html')

def today_cases(request):
    url = 'https://disease.sh/v3/covid-19/countries'
    api_request = requests.get(url)

    if api_request.status_code != 200:
        print("failed to fetch the API...")
        quit()

    response = api_request.json()
    covid_today_cases = {}
    for country in response:
        if country["countryInfo"]["iso2"] == None:
            continue 

        covid_today_cases[country["countryInfo"]["iso2"].lower()] = country["todayCases"]


    world_map = pygal.maps.world.World()
    world_map.style = RS('#37807F', base_style=LCS)
    world_map.add('covid today cases', covid_today_cases)
    world_map.render_to_file('covid_stats/static/covid_stats/images/today_cases.svg')

    return render(request, 'covid_stats/today_cases.html')

def total_deaths(request):
    url = 'https://disease.sh/v3/covid-19/countries'
    api_request = requests.get(url)

    if api_request.status_code != 200:
        print("failed to fetch the API...")
        quit()

    response = api_request.json()
    covid_total_deaths = {}
    for country in response:
        if country["countryInfo"]["iso2"] == None:
            continue 

        covid_total_deaths[country["countryInfo"]["iso2"].lower()] = country["deaths"]


    world_map = pygal.maps.world.World()
    world_map.style = RS('#338BFF', base_style=LCS)
    world_map.add('covid total deaths', covid_total_deaths)
    world_map.render_to_file('covid_stats/static/covid_stats/images/total_deaths.svg')

    return render(request, 'covid_stats/total_deaths.html')

def cases_per_one_million(request):
    url = 'https://disease.sh/v3/covid-19/countries'
    api_request = requests.get(url)

    if api_request.status_code != 200:
        print("failed to fetch the API...")
        quit()

    response = api_request.json()
    covid_cases_per_one_million = {}
    for country in response:
        if country["countryInfo"]["iso2"] == None:
            continue 

        covid_cases_per_one_million[country["countryInfo"]["iso2"].lower()] = country["casesPerOneMillion"]


    world_map = pygal.maps.world.World()
    world_map.style = RS('#478641', base_style=LCS)
    world_map.add('covid cases per one million', covid_cases_per_one_million)
    world_map.render_to_file('covid_stats/static/covid_stats/images/cases_per_one_million.svg')

    return render(request, 'covid_stats/cases_per_one_million.html')

covid_stats/templates/covid_stats/base.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href="{% url 'covid_stats:index' %}">Home</a>
          <a class="nav-link" href="{% url 'covid_stats:world_population' %}">World Population Map</a>
          <a class="nav-link" href="{% url 'covid_stats:covid_total_cases' %}">Covid-19 Total Cases Map</a>
          <a class="nav-link" href="{% url 'covid_stats:today_cases' %}">Covid-19 Today Cases Map</a>
          <a class="nav-link" href="{% url 'covid_stats:total_deaths' %}">Covid-19 Total Deaths Map</a>
          <a class="nav-link" href="{% url 'covid_stats:cases_per_one_million' %}">Covid-19 Cases Per One Million</a>      
        </div>
      </div>
    </div>
</nav>
{% block content %}{% endblock content %} 

covid_stats/templates/covid_stats/cases_per_one_million.html
{% extends "covid_stats/base.html" %}
{% load static %}
{% block content %}
    <object type="image/svg+xml" data="{% static 'covid_stats/images/cases_per_one_million.svg' %}"></object>
{% endblock content %}

covid_stats/templates/covid_stats/covid_total_cases.html
{% extends "covid_stats/base.html" %}
{% load static %}
{% block content %}
    <object type="image/svg+xml" data="{% static 'covid_stats/images/covid_total_cases.svg' %}"></object>
{% endblock content %}

covid_stats/templates/covid_stats/index.html
{% extends "covid_stats/base.html" %}
{% load static %}
{% block content %}
<style>
    .center {
      margin: auto;
      width: 80%;
      border: 3px solid #9370DB;
      padding: 10px; 
      margin: 120px; 
    }
</style>
<div class="center"><p><b>this covid-19 tracker web application displays interactive world maps that contain 
    some covid-19 statistics such as: total cases per country, cases per one million people per country,
    daily cases per country, total deaths per country ..</b></p></div>
{% endblock content %}

covid_stats/templates/covid_stats/today_cases.html
{% extends "covid_stats/base.html" %}
{% load static %}
{% block content %}
    <object type="image/svg+xml" data="{% static 'covid_stats/images/today_cases.svg' %}"></object>
{% endblock content %}

covid_stats/templates/covid_stats/total_deaths.html
{% extends "covid_stats/base.html" %}
{% load static %}
{% block content %}
    <object type="image/svg+xml" data="{% static 'covid_stats/images/total_deaths.svg' %}"></object>
{% endblock content %}

covid_stats/templates/covid_stats/world_population.html
{% extends "covid_stats/base.html" %}
{% load static %}
{% block content %}
    <object type="image/svg+xml" data="{% static 'covid_stats/images/world_population.svg' %}"></object>
{% endblock content %}